[package]
name = "qso-server"
version.workspace = true
edition.workspace = true

[[bin]]
name = "qso-server"
path = "src/main.rs"

[dependencies]
qso-core = { path = "../qso-core" }
rocket = { version = "0.5", features = ["json"] }
reqwest = { version = "0.12", features = ["json", "rustls-tls"], default-features = false }
tokio = { version = "1", features = ["full"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
toml = "0.8"
